config/routes.rb
Rails.application.routes.draw do
  resources :attendances
  resources :events
  resources :testimonials
  resources :news
  resources :enrollment_forms
  resources :posts
  # root to: 'pages#nccflag'

  devise_for :users

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  get 'pages/home'
  get 'pages/aims'
  get 'pages/history'
  get 'pages/nccsong'
  get 'pages/motto'
  get 'pages/nccflag'
  get 'pages/nccrules' # only for PDFs
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  end

app/models/alumni.rb
class Alumni < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
end

app/models/enrollment_form.rb
class EnrollmentForm < ApplicationRecord
end

app/models/event.rb
class Event < ApplicationRecord
end

app/models/news.rb
class News < ApplicationRecord
end

app/models/testimonial.rb
class Testimonial < ApplicationRecord
end

app/models/upload.rb
class Upload < ApplicationRecord
  has_attached_file :image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/enrollment_forms_controller.rb
class EnrollmentFormsController < ApplicationController
  before_action :set_enrollment_form, only: [:show, :edit, :update, :destroy]

  # GET /enrollment_forms
  # GET /enrollment_forms.json
  def index
    @enrollment_forms = EnrollmentForm.all
  end

  # GET /enrollment_forms/1
  # GET /enrollment_forms/1.json
  def show
  end

  # GET /enrollment_forms/new
  def new
    @enrollment_form = EnrollmentForm.new
  end

  # GET /enrollment_forms/1/edit
  def edit
  end

  # POST /enrollment_forms
  # POST /enrollment_forms.json
  def create
    @enrollment_form = EnrollmentForm.new(enrollment_form_params)

    respond_to do |format|
      if @enrollment_form.save
        format.html { redirect_to @enrollment_form, notice: 'Enrollment form was successfully created.' }
        format.json { render :show, status: :created, location: @enrollment_form }
      else
        format.html { render :new }
        format.json { render json: @enrollment_form.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /enrollment_forms/1
  # PATCH/PUT /enrollment_forms/1.json
  def update
    respond_to do |format|
      if @enrollment_form.update(enrollment_form_params)
        format.html { redirect_to @enrollment_form, notice: 'Enrollment form was successfully updated.' }
        format.json { render :show, status: :ok, location: @enrollment_form }
      else
        format.html { render :edit }
        format.json { render json: @enrollment_form.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /enrollment_forms/1
  # DELETE /enrollment_forms/1.json
  def destroy
    @enrollment_form.destroy
    respond_to do |format|
      format.html { redirect_to enrollment_forms_url, notice: 'Enrollment form was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_enrollment_form
      @enrollment_form = EnrollmentForm.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def enrollment_form_params
      params.require(:enrollment_form).permit(:middle_name, :last_name, :branch, :reg_no, :roll_no, :semester, :blood_group, :nationality, :dob, :address, :state, :pincode, :parent_name, :parent_phone, :parent_email, :phone, :email_id, :language, :highest_education, :marks, :year_of_study, :achievement_ncc, :achievement_sport, :achievement_art, :achievement_other, :fill_place, :fill_date)
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name, :tagline, :description, :location, :spoc, :start_date, :end_date)
    end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  before_action :set_news, only: [:show, :edit, :update, :destroy]

  # GET /news
  # GET /news.json
  def index
    @news = News.all
  end

  # GET /news/1
  # GET /news/1.json
  def show
  end

  # GET /news/new
  def new
    @news = News.new
  end

  # GET /news/1/edit
  def edit
  end

  # POST /news
  # POST /news.json
  def create
    @news = News.new(news_params)

    respond_to do |format|
      if @news.save
        format.html { redirect_to @news, notice: 'News was successfully created.' }
        format.json { render :show, status: :created, location: @news }
      else
        format.html { render :new }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /news/1
  # PATCH/PUT /news/1.json
  def update
    respond_to do |format|
      if @news.update(news_params)
        format.html { redirect_to @news, notice: 'News was successfully updated.' }
        format.json { render :show, status: :ok, location: @news }
      else
        format.html { render :edit }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /news/1
  # DELETE /news/1.json
  def destroy
    @news.destroy
    respond_to do |format|
      format.html { redirect_to news_index_url, notice: 'News was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_news
      @news = News.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def news_params
      params.require(:news).permit(:heading, :message, :icon)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/enrollment_forms_helper.rb
module EnrollmentFormsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/testimonials_helper.rb
module TestimonialsHelper
end

app/views/enrollment_forms/_form.html.erb
<%= form_with(model: enrollment_form, local: true) do |form| %>
  <% if enrollment_form.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(enrollment_form.errors.count, "error") %> prohibited this enrollment_form from being saved:</h2>

      <ul>
        <% enrollment_form.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :middle_name %>
    <%= form.datetime_select :middle_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_area :last_name %>
  </div>

  <div class="field">
    <%= form.label :branch %>
    <%= form.number_field :branch %>
  </div>

  <div class="field">
    <%= form.label :reg_no %>
    <%= form.number_field :reg_no %>
  </div>

  <div class="field">
    <%= form.label :roll_no %>
    <%= form.text_field :roll_no %>
  </div>

  <div class="field">
    <%= form.label :semester %>
    <%= form.number_field :semester %>
  </div>

  <div class="field">
    <%= form.label :blood_group %>
    <%= form.text_field :blood_group %>
  </div>

  <div class="field">
    <%= form.label :nationality %>
    <%= form.text_field :nationality %>
  </div>

  <div class="field">
    <%= form.label :dob %>
    <%= form.date_select :dob %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_area :address %>
  </div>

  <div class="field">
    <%= form.label :state %>
    <%= form.text_field :state %>
  </div>

  <div class="field">
    <%= form.label :pincode %>
    <%= form.number_field :pincode %>
  </div>

  <div class="field">
    <%= form.label :parent_name %>
    <%= form.text_field :parent_name %>
  </div>

  <div class="field">
    <%= form.label :parent_phone %>
    <%= form.number_field :parent_phone %>
  </div>

  <div class="field">
    <%= form.label :parent_email %>
    <%= form.text_field :parent_email %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.number_field :phone %>
  </div>

  <div class="field">
    <%= form.label :email_id %>
    <%= form.text_field :email_id %>
  </div>

  <div class="field">
    <%= form.label :language %>
    <%= form.number_field :language %>
  </div>

  <div class="field">
    <%= form.label :highest_education %>
    <%= form.text_field :highest_education %>
  </div>

  <div class="field">
    <%= form.label :marks %>
    <%= form.text_field :marks %>
  </div>

  <div class="field">
    <%= form.label :year_of_study %>
    <%= form.number_field :year_of_study %>
  </div>

  <div class="field">
    <%= form.label :achievement_ncc %>
    <%= form.text_area :achievement_ncc %>
  </div>

  <div class="field">
    <%= form.label :achievement_sport %>
    <%= form.text_area :achievement_sport %>
  </div>

  <div class="field">
    <%= form.label :achievement_art %>
    <%= form.text_area :achievement_art %>
  </div>

  <div class="field">
    <%= form.label :achievement_other %>
    <%= form.text_area :achievement_other %>
  </div>

  <div class="field">
    <%= form.label :fill_place %>
    <%= form.text_field :fill_place %>
  </div>

  <div class="field">
    <%= form.label :fill_date %>
    <%= form.datetime_select :fill_date %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/enrollment_forms/edit.html.erb
<h1>Editing Enrollment Form</h1>

<%= render 'form', enrollment_form: @enrollment_form %>

<%= link_to 'Show', @enrollment_form %> |
<%= link_to 'Back', enrollment_forms_path %>

app/views/enrollment_forms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Enrollment Forms</h1>

<table>
  <thead>
    <tr>
      <th>Middle name</th>
      <th>Last name</th>
      <th>Branch</th>
      <th>Reg no</th>
      <th>Roll no</th>
      <th>Semester</th>
      <th>Blood group</th>
      <th>Nationality</th>
      <th>Dob</th>
      <th>Address</th>
      <th>State</th>
      <th>Pincode</th>
      <th>Parent name</th>
      <th>Parent phone</th>
      <th>Parent email</th>
      <th>Phone</th>
      <th>Email</th>
      <th>Language</th>
      <th>Highest education</th>
      <th>Marks</th>
      <th>Year of study</th>
      <th>Achievement ncc</th>
      <th>Achievement sport</th>
      <th>Achievement art</th>
      <th>Achievement other</th>
      <th>Fill place</th>
      <th>Fill date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @enrollment_forms.each do |enrollment_form| %>
      <tr>
        <td><%= enrollment_form.middle_name %></td>
        <td><%= enrollment_form.last_name %></td>
        <td><%= enrollment_form.branch %></td>
        <td><%= enrollment_form.reg_no %></td>
        <td><%= enrollment_form.roll_no %></td>
        <td><%= enrollment_form.semester %></td>
        <td><%= enrollment_form.blood_group %></td>
        <td><%= enrollment_form.nationality %></td>
        <td><%= enrollment_form.dob %></td>
        <td><%= enrollment_form.address %></td>
        <td><%= enrollment_form.state %></td>
        <td><%= enrollment_form.pincode %></td>
        <td><%= enrollment_form.parent_name %></td>
        <td><%= enrollment_form.parent_phone %></td>
        <td><%= enrollment_form.parent_email %></td>
        <td><%= enrollment_form.phone %></td>
        <td><%= enrollment_form.email_id %></td>
        <td><%= enrollment_form.language %></td>
        <td><%= enrollment_form.highest_education %></td>
        <td><%= enrollment_form.marks %></td>
        <td><%= enrollment_form.year_of_study %></td>
        <td><%= enrollment_form.achievement_ncc %></td>
        <td><%= enrollment_form.achievement_sport %></td>
        <td><%= enrollment_form.achievement_art %></td>
        <td><%= enrollment_form.achievement_other %></td>
        <td><%= enrollment_form.fill_place %></td>
        <td><%= enrollment_form.fill_date %></td>
        <td><%= link_to 'Show', enrollment_form %></td>
        <td><%= link_to 'Edit', edit_enrollment_form_path(enrollment_form) %></td>
        <td><%= link_to 'Destroy', enrollment_form, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Enrollment Form', new_enrollment_form_path %>

app/views/enrollment_forms/new.html.erb
<h1>New Enrollment Form</h1>

<%= render 'form', enrollment_form: @enrollment_form %>

<%= link_to 'Back', enrollment_forms_path %>

app/views/enrollment_forms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Middle name:</strong>
  <%= @enrollment_form.middle_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @enrollment_form.last_name %>
</p>

<p>
  <strong>Branch:</strong>
  <%= @enrollment_form.branch %>
</p>

<p>
  <strong>Reg no:</strong>
  <%= @enrollment_form.reg_no %>
</p>

<p>
  <strong>Roll no:</strong>
  <%= @enrollment_form.roll_no %>
</p>

<p>
  <strong>Semester:</strong>
  <%= @enrollment_form.semester %>
</p>

<p>
  <strong>Blood group:</strong>
  <%= @enrollment_form.blood_group %>
</p>

<p>
  <strong>Nationality:</strong>
  <%= @enrollment_form.nationality %>
</p>

<p>
  <strong>Dob:</strong>
  <%= @enrollment_form.dob %>
</p>

<p>
  <strong>Address:</strong>
  <%= @enrollment_form.address %>
</p>

<p>
  <strong>State:</strong>
  <%= @enrollment_form.state %>
</p>

<p>
  <strong>Pincode:</strong>
  <%= @enrollment_form.pincode %>
</p>

<p>
  <strong>Parent name:</strong>
  <%= @enrollment_form.parent_name %>
</p>

<p>
  <strong>Parent phone:</strong>
  <%= @enrollment_form.parent_phone %>
</p>

<p>
  <strong>Parent email:</strong>
  <%= @enrollment_form.parent_email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @enrollment_form.phone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @enrollment_form.email_id %>
</p>

<p>
  <strong>Language:</strong>
  <%= @enrollment_form.language %>
</p>

<p>
  <strong>Highest education:</strong>
  <%= @enrollment_form.highest_education %>
</p>

<p>
  <strong>Marks:</strong>
  <%= @enrollment_form.marks %>
</p>

<p>
  <strong>Year of study:</strong>
  <%= @enrollment_form.year_of_study %>
</p>

<p>
  <strong>Achievement ncc:</strong>
  <%= @enrollment_form.achievement_ncc %>
</p>

<p>
  <strong>Achievement sport:</strong>
  <%= @enrollment_form.achievement_sport %>
</p>

<p>
  <strong>Achievement art:</strong>
  <%= @enrollment_form.achievement_art %>
</p>

<p>
  <strong>Achievement other:</strong>
  <%= @enrollment_form.achievement_other %>
</p>

<p>
  <strong>Fill place:</strong>
  <%= @enrollment_form.fill_place %>
</p>

<p>
  <strong>Fill date:</strong>
  <%= @enrollment_form.fill_date %>
</p>

<%= link_to 'Edit', edit_enrollment_form_path(@enrollment_form) %> |
<%= link_to 'Back', enrollment_forms_path %>