config/routes.rb
Rails.application.routes.draw do
  resources :attendances
  resources :events
  resources :testimonials
  resources :news
  resources :enrollment_forms
  resources :posts
  # root to: 'pages#nccflag'

  devise_for :users

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  get 'pages/home'
  get 'pages/aims'
  get 'pages/history'
  get 'pages/nccsong'
  get 'pages/motto'
  get 'pages/nccflag'
  get 'pages/nccrules' # only for PDFs
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  end

app/models/testimonial.rb
class Testimonial < ApplicationRecord
end

app/controllers/testimonials_controller.rb
class TestimonialsController < ApplicationController
  before_action :set_testimonial, only: [:show, :edit, :update, :destroy]

  # GET /testimonials
  # GET /testimonials.json
  def index
    @testimonials = Testimonial.all
  end

  # GET /testimonials/1
  # GET /testimonials/1.json
  def show
  end

  # GET /testimonials/new
  def new
    @testimonial = Testimonial.new
  end

  # GET /testimonials/1/edit
  def edit
  end

  # POST /testimonials
  # POST /testimonials.json
  def create
    @testimonial = Testimonial.new(testimonial_params)

    respond_to do |format|
      if @testimonial.save
        format.html { redirect_to @testimonial, notice: 'Testimonial was successfully created.' }
        format.json { render :show, status: :created, location: @testimonial }
      else
        format.html { render :new }
        format.json { render json: @testimonial.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /testimonials/1
  # PATCH/PUT /testimonials/1.json
  def update
    respond_to do |format|
      if @testimonial.update(testimonial_params)
        format.html { redirect_to @testimonial, notice: 'Testimonial was successfully updated.' }
        format.json { render :show, status: :ok, location: @testimonial }
      else
        format.html { render :edit }
        format.json { render json: @testimonial.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /testimonials/1
  # DELETE /testimonials/1.json
  def destroy
    @testimonial.destroy
    respond_to do |format|
      format.html { redirect_to testimonials_url, notice: 'Testimonial was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_testimonial
      @testimonial = Testimonial.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def testimonial_params
      params.require(:testimonial).permit(:name, :phone, :facebook, :linkedin, :instagram, :email, :statement)
    end
end

app/helpers/testimonials_helper.rb
module TestimonialsHelper
end

app/views/testimonials/_form.html.erb
<%= form_with(model: testimonial, local: true) do |form| %>
  <% if testimonial.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(testimonial.errors.count, "error") %> prohibited this testimonial from being saved:</h2>

      <ul>
        <% testimonial.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.number_field :phone %>
  </div>

  <div class="field">
    <%= form.label :facebook %>
    <%= form.text_field :facebook %>
  </div>

  <div class="field">
    <%= form.label :linkedin %>
    <%= form.text_field :linkedin %>
  </div>

  <div class="field">
    <%= form.label :instagram %>
    <%= form.text_field :instagram %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :statement %>
    <%= form.text_area :statement %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/testimonials/edit.html.erb
<h1>Editing Testimonial</h1>

<%= render 'form', testimonial: @testimonial %>

<%= link_to 'Show', @testimonial %> |
<%= link_to 'Back', testimonials_path %>

app/views/testimonials/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Testimonials</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Phone</th>
      <th>Facebook</th>
      <th>Linkedin</th>
      <th>Instagram</th>
      <th>Email</th>
      <th>Statement</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @testimonials.each do |testimonial| %>
      <tr>
        <td><%= testimonial.name %></td>
        <td><%= testimonial.phone %></td>
        <td><%= testimonial.facebook %></td>
        <td><%= testimonial.linkedin %></td>
        <td><%= testimonial.instagram %></td>
        <td><%= testimonial.email %></td>
        <td><%= testimonial.statement %></td>
        <td><%= link_to 'Show', testimonial %></td>
        <td><%= link_to 'Edit', edit_testimonial_path(testimonial) %></td>
        <td><%= link_to 'Destroy', testimonial, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Testimonial', new_testimonial_path %>

app/views/testimonials/new.html.erb
<h1>New Testimonial</h1>

<%= render 'form', testimonial: @testimonial %>

<%= link_to 'Back', testimonials_path %>

app/views/testimonials/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @testimonial.name %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @testimonial.phone %>
</p>

<p>
  <strong>Facebook:</strong>
  <%= @testimonial.facebook %>
</p>

<p>
  <strong>Linkedin:</strong>
  <%= @testimonial.linkedin %>
</p>

<p>
  <strong>Instagram:</strong>
  <%= @testimonial.instagram %>
</p>

<p>
  <strong>Email:</strong>
  <%= @testimonial.email %>
</p>

<p>
  <strong>Statement:</strong>
  <%= @testimonial.statement %>
</p>

<%= link_to 'Edit', edit_testimonial_path(@testimonial) %> |
<%= link_to 'Back', testimonials_path %>